### ISSUE TITLE
既存改修 > ダッシュボード

### ISSUE THREAD

**Issue by MasatakaItoh** [thanklet/mock-dapp-prototype#27]
## 対応すること

- アバター画像を追加。クリックしたらプロフィール画面に遷移
- Walletボタンを追加。クリックしたらapp wallet画面に遷移
- Swap、Stakingボタンを削除し、Thanksボタンだけを残す

## デザイン

https://www.figma.com/design/o0IzRnD4RKvoWcL02ZjaO8/Thanklet-Mock?node-id=14-151&node-type=frame&t=w120V5NSyMQmSkx6-0

![ ](https://i.gyazo.com/c00108fe0e155c500a047d243e84ac25.png)

**Comment by MasatakaItoh** [comment]
@yuki-yamamura 
既存画面の改修ですが、軽微なのでこちらもご対応お願いします 🙏

**Comment by yuki-yamamura** [comment]
@MasatakaItoh 
承知しました！
