### ISSUE TITLE
9月分開発の設計

### ISSUE THREAD

**Issue by ryosuke-sato-51** [thanklet/mock-dapp-prototype#4]
### フロントエンド
- React
- React Router
- TypeScript
- Vite
- MUI（Vuexy）

### BaaS
- Firebase

### その他
- Bun（いい感じに使えたら。難しそうならnpmでもyarnでも）
- biome（いい感じに使えたら。難しそうならESLintとPrettier）

### JavaScriptランタイム
ランタイムはBunを使いたい。NetlifyでもBun使えるっぽいので大丈夫そう。
https://www.netlify.com/blog/bun-support-in-builds/

### フロントエンド
React + TS + Viteで環境作成する。この辺見ながらで大丈夫そう。
https://ja.vitejs.dev/guide/
https://zenn.dev/kazukix/articles/react-setup-2024

### ディレクトリ
[bulletproof-react](https://github.com/alan2207/bulletproof-react/tree/master)にreact-viteがあるので、これをベースにする

### BaaS
共有してもらったFirebaseを繋げる。以下見ながらでいけそう。
https://firebase.google.com/docs/web/setup?hl=ja
https://zenn.dev/conecone/articles/058755b87fec41
https://qiita.com/Naoya_pro/items/a42f1ecae8acce249ef3#firebase%E5%81%B4%E3%81%AE%E8%A8%AD%E5%AE%9A

### Linter Formatter
biomeだと、これひとつでLinterとFormatterを兼ねているので使いたい。あと早いっぽい。

## マークアップ方針
基本はMUIで作る。
Vuexyはローカルで立ち上げると、色々な管理画面のパターンが見れるので（キャプチャの感じ）そのまま持ってこれそうであればそのコードを使う。
MUIで作られているので、おそらく問題なく使える。
うまくいかなければ、以下の依存関係をチェックする
https://demos.pixinvent.com/vuexy-nextjs-admin-template/documentation/docs/guide/overview/dependencies

<img width="1266" alt="スクリーンショット 2024-09-12 23 05 38" src="https://github.com/user-attachments/assets/3083a818-e9a1-4fd8-8930-6f22dda6602c">

## DB
Thanksを送れる機能だけ作成するので、DBが必要。Cloud Firestoreで作成。

### userコレクション
ユーザーのコレクション。アカウント作成機能はないので、手動で入れておく想定

| key | value | 
| --------- | --------- | 
| id  | string     | 
| name | string     | 
| image_path  | string     | 
| thanks  | number     | 

### transaction_historyコレクション
Thanksの送信履歴

| key | value | 
| --------- | --------- | 
| id  | string     | 
| thanks | number     | 
| emoji  | string     | 
| created_at  | date     | 
| send_user_id | string     | 
| receive_user_id  | string     | 

※どれくらいちゃんと作るか分からないが、キャプチャの画面で受け取ったことを１回確認したら、「You have received a Thank You!」をもう出さないようにする必要ある？もし必要ならis_confirmedフィールドが必要

![スクリーンショット 2024-09-12 23 57 36](https://github.com/user-attachments/assets/cbd1f78e-f8a9-4f4a-990c-ff25e22777b9)

#### ユーザー一覧
URL：/admin/users

- 表示するユーザーはconstantsディレクトリに手書きで書いておく
- グラフは画像でOK
- チェックボックスやセレクトボックスは操作できるくらいに作っておかないといけない？

![スクリーンショット 2024-09-13 0 02 53](https://github.com/user-attachments/assets/20036528-b894-42c7-aa2f-04ab7eb945bc)

#### ユーザー詳細
URL：/admin/users/[userId]

- 表示するユーザー情報や、履歴はconstantsディレクトリに手書きで書いておく
- チェックボックスやセレクトボックスは操作できるくらいに作っておかないといけない？

![スクリーンショット 2024-09-13 0 05 14](https://github.com/user-attachments/assets/e7fb010f-8b98-4451-ad9f-e681f872ec52)

#### 送信側ダッシュボード
URL：/app/[userId]/dashboard

- クエリパラメータのuserIdからユーザー情報を取得
- 送信履歴はtransaction-historyを取得して、sentUserIdとuserIdが一致するドキュメントを表示すれば出来る
- userコレクションとtransaction-historyコレクションにリレーションを持たせた方がいいけど、FirestoreがNoSQLなので、やり方調べる必要ある。余裕なければとりあえず上記の方法で実現する

![スクリーンショット 2024-09-13 0 17 59](https://github.com/user-attachments/assets/31239eba-4260-4bcc-a246-49576e48c456)

#### 受け取り側ダッシュボード
URL：/app/[userId]/dashboard

- クエリパラメータのuserIdからユーザー情報を取得
- 受信履歴はtransaction-historyを取得して、receiveUserIdとuserIdが一致するドキュメントを表示すれば出来る
- userコレクションとtransaction-historyコレクションにリレーションを持たせた方がいいけど、FirestoreがNoSQLなので、やり方調べる必要ある。余裕なければとりあえず上記の方法で実現する
- Thanksを受け取った表示は、一回確認したら表示しない？
- Thanksを複数受け取っていたら、どのように表示する？どこまで作り込む必要があるかは要確認

![スクリーンショット 2024-09-13 0 20 59](https://github.com/user-attachments/assets/a4c1dd4a-5921-4aed-a456-5adb38fadb62)

#### 送信先選択ページ
URL：/app/[userId]/thanks/location

- マップは固定でOK。ピンは表示させとく必要あり？
- 送信先一覧は、DBで持っているuserデータをフロントで手書きしておいて、それを表示する感じで良いかな

![スクリーンショット 2024-09-13 0 26 49](https://github.com/user-attachments/assets/ff28cbfd-4d3e-4fb5-a8e0-900c86c45a0c)

#### thanks送信ページ
URL：/app/[userId]/thanks/send/[recieveUserId]

- 表示するユーザーは、DBで持っているuserデータをフロントで手書きしておいて、それを表示する感じで良いかな
- 絵文字は２〜３パターンくらいにしておく
- Thanksボタンクリックで、transaction-historyのドキュメント作成。sendUserIdとreceiveUserIdはクエリパラメーターから取得
- POST成功したら、Sent ThanksのUIを表示する

![スクリーンショット 2024-09-13 0 33 26](https://github.com/user-attachments/assets/31c2c1df-fa23-4875-8456-c3dd2e9695a1)

**Comment by MasatakaItoh** [comment]
@ryosuke-sato-51 

ちょっと時間なくてザックリしか確認できてないですが、コメントしておきます！

> biomeだと、これひとつでLinterとFormatterを兼ねているので使いたい。あと早いっぽい。

biome + lefthookはやくて良いかもです！

> DB

カラム名の命名をスネークに統一いただけると！

リレーションは[これ](https://qiita.com/keito_jp/items/3a9a14c9e0fb951152f7#%E4%BB%A3%E8%A1%A8%E7%9A%84%E3%81%AA%E3%83%AA%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%B7%E3%83%83%E3%83%97)？
自分もNoSQL詳しくないので、着手前だったらSupabaseに変えるのも検討して良いかも。。ミスったな。。

> ※どれくらいちゃんと作るか分からないが、キャプチャの画面で受け取ったことを１回確認したら、「You have received a Thank You!」をもう出さないようにする必要ある？もし必要ならis_confirmedフィールドが必要

こちらはなしで！
けど、Thanks一覧画面の仕様は確認したいですね

> 表示するユーザーはconstantsディレクトリに手書きで書いておく

一応後工程を考慮しておくと、ViteだとTanstackとかでクライアントフェッチになると思う＝データフェッチをコロケーションすることになるので、featureコンポーネントファイルにベタ書きで良いです！

> チェックボックスやセレクトボックスは操作できるくらいに作っておかないといけない？

押したらチェックがつく程度には作って欲しいです。MUIなのでデフォルトでチェックの挙動はついてるはず

> クエリパラメータのuserIdからユーザー情報を取得

~~本来認証後の画面で、userIdはパスに現れないので、localStorageやcookie、envに持つなどで実装できますか？~~

他のユーザーのダッシュボードを見れるようにするか次第か

見れるなら

- パスネームにuserIdを入れる
- ダッシュボード画面のGETにはパスネームのuserIdを利用
- それ以外の画面のGET/POSTにはlocalStorageやcookie、envに持ったuserIdを利用

見れないなら

- パスネームにuserIdを入れない
- GET/POSTにはlocalStorageやcookie、envに持ったuserIdを利用

とりあえず工数少ない方で良いかと！

**Comment by ryosuke-sato-51** [comment]
@MasatakaItoh 
> カラム名の命名をスネークに統一いただけると！

これは修正しました！

>リレーションは[これ](https://qiita.com/keito_jp/items/3a9a14c9e0fb951152f7#%E4%BB%A3%E8%A1%A8%E7%9A%84%E3%81%AA%E3%83%AA%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%B7%E3%83%83%E3%83%97)？
自分もNoSQL詳しくないので、着手前だったらSupabaseに変えるのも検討して良いかも。。ミスったな。。

10月分の実装含めて、おそらくそこまで複雑なことをDBで実装する必要はないかと思うのでとりあえずFirebaseで問題ないかなーと思います！
NoSQLでもリレーションのような機能は実装できると思うので、やりながら検討します！

>こちらはなしで！
けど、Thanks一覧画面の仕様は確認したいですね

了解です！とりあえず水曜日のMTGで確認してから考える。で良さそうですね。

> 一応後工程を考慮しておくと、ViteだとTanstackとかでクライアントフェッチになると思う＝データフェッチをコロケーションすることになるので、featureコンポーネントファイルにベタ書きで良いです！

管理者画面ではfeatureコンポーネントファイルにベタ書きで良さそうですね。
ユーザー画面では「送信先選択ページ」と「thanks送信ページ」に表示するユーザー情報は、DBと同じ情報を表示したら良いと考えていました。
なのでフロントエンドのコードに、DBと同じデータを置いておこうと思っているので、constantsディレクトリに書いておいても良いかなって感じです。
でもどちらでも良い。っていう範囲内かと思うので、コード書きながらやっていきますね。

>押したらチェックがつく程度には作って欲しいです。MUIなのでデフォルトでチェックの挙動はついてるはず

確かにデフォルトで動きますねw
であれば工数も変わらないので問題ないですー。

>本来認証後の画面で、userIdはパスに現れないので、localStorageやcookie、envに持つなどで実装できますか？
他のユーザーのダッシュボードを見れるようにするか次第か

本来はログインユーザーのuserIdはパスに表示しないか。それがすっぽり頭から抜けてました。
ただコメントしてもらった通り、ダッシュボードでは送信側と受信側で、別ユーザーとして閲覧できる必要があると思うので、
ここはURLに含めて、他画面ではenvから参照する感じにしようと思います！
